dist: trusty
language: go
go:
  - 1.8
  - 1.9
install:
  - go get -v github.com/mattn/go-sqlite3
  - go install -v -x github.com/mattn/go-sqlite3
script: 
  - make
  - make test
  - go run marlowc/main.go -input examples/library/models -stdout=true
  - go run marlowc/main.go -input examples/library/models
  - go run examples/library/main.go

after_success:
  - bash <(curl -s https://codecov.io/bash)
