dist: trusty
language: go
go:
  - 1.8
  - 1.9
install:
  - go get -v github.com/mattn/go-sqlite3
  - go install -v -x github.com/mattn/go-sqlite3
  - go get -v github.com/modocache/gover
script: 
  - make
  - make test
  - gover ./marlow ./coverage.txt
  - make test-example
  - go run marlowc/main.go -input examples/library/models -stdout=true
  - make example
after_success:
  - bash <(curl -s https://codecov.io/bash)
